### ISSUE TITLE
app configs not working properly for Bristol

### ISSUE THREAD

**Issue by carimura** [carimura/vista#16]
@zootalures -- I haven't reproduced this... can you paste your version of Fn server and CLI? This is definitely a big issue and want to make sure we solve it because app configs are important.

**Comment by zootalures** [comment]
``` 
$fn version                                                                                                                                                                                                               
Client version: 0.3.55
Server version 0.3.56
```
but that's built off master as of df34c1361b37426d34ae7762d99e9af9270f0b96

**Comment by zootalures** [comment]
Will double check and try to reproduce when I have some time.
